import fs from 'fs';
import path from 'path';
import { themeColors, ColorPalette, semanticColors } from '../src/lib/tokens/colors';

function generateCSSVariables() {
  let cssContent = `/* Auto-generated CSS variables from colors.ts */
/* This file is automatically generated. Do not edit manually. */

:root {
  /* 기본 CSS 변수들 */
  --radius: 0.625rem;
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.145 0 0);
  --popover: oklch(1 0 0);
  --popover-foreground: oklch(0.145 0 0);
  --primary: oklch(0.205 0 0);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.97 0 0);
  --secondary-foreground: oklch(0.205 0 0);
  --customer: oklch(0.105 0 0);
  --customer-foreground: oklch(0.785 0 0);
  --muted: oklch(0.97 0 0);
  --muted-foreground: oklch(0.556 0 0);
  --accent: oklch(0.97 0 0);
  --accent-foreground: oklch(0.205 0 0);
  --destructive: oklch(0.577 0.245 27.325);
  --border: oklch(0.922 0 0);
  --input: oklch(0.922 0 0);
  --ring: oklch(0.708 0 0);
  --chart-1: oklch(0.646 0.222 41.116);
  --chart-2: oklch(0.6 0.118 184.704);
  --chart-3: oklch(0.398 0.07 227.392);
  --chart-4: oklch(0.828 0.189 84.429);
  --chart-5: oklch(0.769 0.188 70.08);
  --sidebar: oklch(0.985 0 0);
  --sidebar-foreground: oklch(0.145 0 0);
  --sidebar-primary: oklch(0.205 0 0);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.97 0 0);
  --sidebar-accent-foreground: oklch(0.205 0 0);
  --sidebar-border: oklch(0.922 0 0);
  --sidebar-ring: oklch(0.708 0 0);

  /* 기본 색상들 (모든 테마에서 공통 사용) */
  /* Secondary 색상 */
  --secondary-50: ${semanticColors.secondary['50'].value};
  --secondary-100: ${semanticColors.secondary['100'].value};
  --secondary-200: ${semanticColors.secondary['200'].value};
  --secondary-300: ${semanticColors.secondary['300'].value};
  --secondary-400: ${semanticColors.secondary['400'].value};
  --secondary-500: ${semanticColors.secondary['500'].value};
  --secondary-600: ${semanticColors.secondary['600'].value};
  --secondary-700: ${semanticColors.secondary['700'].value};
  --secondary-800: ${semanticColors.secondary['800'].value};
  --secondary-900: ${semanticColors.secondary['900'].value};
  --secondary-950: ${semanticColors.secondary['950'].value};

  /* Success 색상 */
  --success-50: ${semanticColors.success['50'].value};
  --success-100: ${semanticColors.success['100'].value};
  --success-200: ${semanticColors.success['200'].value};
  --success-300: ${semanticColors.success['300'].value};
  --success-400: ${semanticColors.success['400'].value};
  --success-500: ${semanticColors.success['500'].value};
  --success-600: ${semanticColors.success['600'].value};
  --success-700: ${semanticColors.success['700'].value};
  --success-800: ${semanticColors.success['800'].value};
  --success-900: ${semanticColors.success['900'].value};
  --success-950: ${semanticColors.success['950'].value};

  /* Warning 색상 */
  --warning-50: ${semanticColors.warning['50'].value};
  --warning-100: ${semanticColors.warning['100'].value};
  --warning-200: ${semanticColors.warning['200'].value};
  --warning-300: ${semanticColors.warning['300'].value};
  --warning-400: ${semanticColors.warning['400'].value};
  --warning-500: ${semanticColors.warning['500'].value};
  --warning-600: ${semanticColors.warning['600'].value};
  --warning-700: ${semanticColors.warning['700'].value};
  --warning-800: ${semanticColors.warning['800'].value};
  --warning-900: ${semanticColors.warning['900'].value};
  --warning-950: ${semanticColors.warning['950'].value};

  /* Error 색상 */
  --error-50: ${semanticColors.error['50'].value};
  --error-100: ${semanticColors.error['100'].value};
  --error-200: ${semanticColors.error['200'].value};
  --error-300: ${semanticColors.error['300'].value};
  --error-400: ${semanticColors.error['400'].value};
  --error-500: ${semanticColors.error['500'].value};
  --error-600: ${semanticColors.error['600'].value};
  --error-700: ${semanticColors.error['700'].value};
  --error-800: ${semanticColors.error['800'].value};
  --error-900: ${semanticColors.error['900'].value};
  --error-950: ${semanticColors.error['950'].value};

  /* 테마별 Primary 색상 변수들 */
`;

  // 테마별 Primary 색상 변수만 생성
  Object.entries(themeColors).forEach(([themeName, colors]) => {
    if (themeName !== 'customer') {
      // Customer 테마는 별도 CSS 변수 생성하지 않음 (동적으로 --primary- 변수 설정)
      // 다른 테마들은 --theme-{name}-primary- 접두사 사용
      cssContent += `  /* ${themeName} 테마 Primary 색상 */\n`;
      Object.entries(colors.primary).forEach(([shade, token]) => {
        cssContent += `  --theme-${themeName}-primary-${shade}: ${token.value};\n`;
      });
      cssContent += '\n';
    }
  });

  cssContent += '}\n\n';

  // 테마별 CSS 클래스 생성 (Primary 색상만)
  Object.entries(themeColors).forEach(([themeName, colors]) => {
    if (themeName !== 'customer') {
      // Customer 테마는 CSS 클래스 생성하지 않음 (동적으로 적용)
      // 다른 테마들은 기존 방식 유지
      cssContent += `.theme-${themeName} {\n`;
      cssContent += `  --primary: var(--theme-${themeName}-primary-500);\n`;
      cssContent += `  --primary-foreground: var(--theme-${themeName}-primary-50);\n`;
      Object.entries(colors.primary).forEach(([shade, token]) => {
        cssContent += `  --primary-${shade}: var(--theme-${themeName}-primary-${shade});\n`;
      });
      cssContent += `}\n\n`;
    }
  });

  // Dark 테마 추가
  cssContent += `.dark {
  --background: oklch(0.145 0 0);
  --foreground: oklch(0.985 0 0);
  --card: oklch(0.205 0 0);
  --card-foreground: oklch(0.985 0 0);
  --popover: oklch(0.205 0 0);
  --popover-foreground: oklch(0.985 0 0);
  --primary: oklch(0.922 0 0);
  --primary-foreground: oklch(0.205 0 0);
  --secondary: oklch(0.269 0 0);
  --secondary-foreground: oklch(0.985 0 0);
  --muted: oklch(0.269 0 0);
  --muted-foreground: oklch(0.708 0 0);
  --accent: oklch(0.269 0 0);
  --accent-foreground: oklch(0.985 0 0);
  --destructive: oklch(0.704 0.191 22.216);
  --border: oklch(1 0 0 / 10%);
  --input: oklch(1 0 0 / 15%);
  --ring: oklch(0.556 0 0);
  --chart-1: oklch(0.488 0.243 264.376);
  --chart-2: oklch(0.696 0.17 162.48);
  --chart-3: oklch(0.769 0.188 70.08);
  --chart-4: oklch(0.627 0.265 303.9);
  --chart-5: oklch(0.645 0.246 16.439);
  --sidebar: oklch(0.205 0 0);
  --sidebar-foreground: oklch(0.985 0 0);
  --sidebar-primary: oklch(0.488 0.243 264.376);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.269 0 0);
  --sidebar-accent-foreground: oklch(0.985 0 0);
  --sidebar-border: oklch(1 0 0 / 10%);
  --sidebar-ring: oklch(0.556 0 0);
}`;

  const outputPath = path.join(__dirname, '../src/app/generated-theme-variables.css');
  fs.writeFileSync(outputPath, cssContent);
  console.log(`✅ Generated optimized CSS variables: ${outputPath}`);
}

generateCSSVariables();
console.log('🎉 Optimized CSS variables generation completed!');
